version: 0.1
phases:
  install:
    commands:
      - npm install request
      - aws cloudformation package --template-file samTemplate.yaml --s3-bucket haolinj-functions-bucket 
                                   --output-template-file NewSamTemplate.yaml
artifacts:
  type: zip
  files:
    - NewSamTemplate.yaml