version: 0.1
phases:
  install:
    commands:
      - npm install
      - aws cloudformation package --template-file vendor-manager.yml --output-template-file vendor-manager-output.yml
artifacts:
  type: zip
  files:
    - vendor-manager-output.yml